//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CirWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat_detalhe
    {
        public int Chat_Detalhe_id { get; set; }
        public int Chat_Master_id { get; set; }
        public System.DateTime Data { get; set; }
        public string Chat_Anunciante { get; set; }
        public string Chat_Usuario { get; set; }
    
        public virtual chat_master chat_master { get; set; }
    }
}
